### ISSUE TITLE
Not working with 100% width/height elements

### ISSUE THREAD

**Issue by raulmatei** [Automattic/antiscroll#44]
I was trying to set it up with 100% width & height elements but it's not working, so I tried to dynamically set the width and height through javascript, it works this way but the div native scrollbars still appear, see image attached
![antiscroll](https://f.cloud.github.com/assets/1718341/108033/07a0885a-6a40-11e2-8933-69038a09206e.jpg)

HTML behind is:

``` html
  <body>
    <div class="box-wrap antiscroll-wrap">
      <div class="box">
        <div class="antiscroll-inner">
          <div class="box-inner">
            ...
          </div>
        </div>
      </div>
    </div>
 </body>
```

The CSS:

``` css
body {
        padding: 0;
        margin: 0;
        overflow: hidden;
      }
```

The JS:

``` javascript
        $(window).on('load resize', function() {
          $('.antiscroll-inner').css({
            height: $(window).height(),
            width: $(window).width(),
          });
        }).resize();
```

**Comment by Lazza** [comment]
Thank you @raulmatei, your fix worked perfectly for me as well.
