### ISSUE TITLE
Releases? Tags?

### ISSUE THREAD

**Issue by loostro** [Automattic/antiscroll#79]
Some tags would be very welcome as it would ease locking dependencies.

**Comment by bennyn** [comment]
+1 (and Bower support please :yum:)

**Comment by nolsherry** [comment]
Hello @nylen ,
I am the member of [cdnjs](https://github.com/cdnjs/cdnjs) project.
We want to host this library.
Please add the version tag into your project, thank you very much!

![image](https://cloud.githubusercontent.com/assets/8747900/18222233/69638694-71c3-11e6-952e-e0cef6ff95af.png)


cdnjs/cdnjs#8434

**Comment by nylen** [comment]
I've tagged the latest version as v0.9:

![image](https://cloud.githubusercontent.com/assets/227022/18602587/46872b4c-7c1f-11e6-8028-f8a2e6b818fc.png)
