### ISSUE TITLE
Please create an initial version

### ISSUE THREAD

**Issue by bennyn** [Automattic/antiscroll#90]
Hi there,

I like your plugin pretty much but it would be nice if you create an intial version (`v1.0`) on GitHub, so that I can use your plugin with a specific version, so that my application doesn't break if you change your plugin.

Your plugin is also listed on http://bower.io/search/ so it would be nice if you add a `bower.json` configuration file. I can help you with that! :)

Cheers from Berlin,

Benny

**Comment by nylen** [comment]
I've tagged the latest version as v0.9:

![image](https://cloud.githubusercontent.com/assets/227022/18602587/46872b4c-7c1f-11e6-8028-f8a2e6b818fc.png)
